version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "mySAMLambda"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1rzusnh8kiwri"
s3_prefix = "mySAMLambda"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = ["HelloWorldFunction=830659593716.dkr.ecr.us-east-1.amazonaws.com/mysamlambdaa71dbffe/helloworldfunction19d43fc4repo"]
